from pathlib import Path
from typing import BinaryIO, Protocol


class FileStorage(Protocol):
    def save_input(self, job_id: str, source: BinaryIO) -> str: ...
    def get_input_path(self, job_id: str) -> Path: ...
    def save_output(self, job_id: str, source_path: Path) -> str: ...
    def get_output_path(self, job_id: str) -> Path: ...
